version: '3.8'
services:
      # Servicio 1: Servidor Express
      backend:
        build:
          context: .
          dockerfile: ./server/Dockerfile
        ports:
          - "3001:3001"
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
        environment:
          - NODE_ENV=development
          - DB_HOST=mysql
          - DB_USER=root
          - DB_PASSWORD=root
          - DB_NAME=beneficio_alimentario
          - DB_PORT=3306
        depends_on:
          - mysql

      # Servicio 2: Portal del Estudiante (Vite/Vue 3)
      frontend-estudiante:
        build:
          context: .
          dockerfile: ./frontend-estudiante/Dockerfile
        ports:
          - "5173:5173"
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
          - /usr/src/app/frontend-estudiante/node_modules
          - /usr/src/app/frontend-core/node_modules
        depends_on:
          - backend

      # Servicio 3: Panel de la Coordinadora (Vite/Vue 3)
      frontend-coordinadora:
        build:
          context: .
          dockerfile: ./frontend-coordinadora/Dockerfile
        ports:
          - "5174:5174"
        volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
          - /usr/src/app/frontend-coordinadora/node_modules
          - /usr/src/app/frontend-core/node_modules
        depends_on:
          - backend

      # Servicio 3: Base de Datos MySQL
      mysql:
        image: mysql:8.0
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: beneficio_alimentario
        volumes:
          - mysql_data:/var/lib/mysql

volumes:
  mysql_data: